version: '3.7'

services:
  chironpy:
    image: chironpy-test
    container_name: chironpy-test
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    volumes:
      - ../:/src
    stdin_open: true
    tty: true
