FROM python:3.13

RUN python -m pip install --upgrade pip uv

WORKDIR /src

CMD uv sync --group dev && uv run jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token='' --NotebookApp.password=''
