version: "3.7"

services:
  traefik:
    image: "traefik:v2.4"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  mkdocs:
    image: chironpy-mkdocs
    container_name: chironpy-mkdocs
    build:
      context: ..
      dockerfile: docker/Dockerfile.mkdocs
    ports:
      - "8000:8000"
    volumes:
      - ../:/src
    stdin_open: true
    tty: true
    depends_on:
      - jupyter
    labels:
      traefik.enable: true
      traefik.http.routers.mkdocs.rule: Host(`mkdocs.chironpy.localhost`)
      traefik.http.routers.mkdocs.entrypoints: web

  jupyter:
    image: chironpy-jupyter
    container_name: chironpy-jupyter
    build:
      context: ..
      dockerfile: docker/Dockerfile.jupyter
    environment:
      - PYTHONPATH=/src:${PYTHONPATH}
    ports:
      - "8889:8888"
    volumes:
      - ../:/src
    stdin_open: true
    tty: true
    depends_on:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.jupyter.rule: Host(`jupyter.chironpy.localhost`)
      traefik.http.routers.jupyter.entrypoints: web
