version: '3.7'

services:
  chironpy:
    image: chironpy-lint
    container_name: chironpy-lint
    build:
      context: ..
      dockerfile: docker/Dockerfile.lint
    volumes:
      - ../:/src
    stdin_open: true
    tty: true
