site_name: chironpy docs

theme:
  name: "material"
  palette:
    primary: "blue grey"
    accent: "red"
  icon:
    logo: logo
    # repo: github

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
      toc_depth: 3

repo_name: chironapp/chironpy
repo_url: https://github.com/chironapp/chironpy

plugins:
  - mknotebooks

nav:
  - "index.md"
  - "Features":
      - "features/Metrics.ipynb"
      - "features/Power duration modelling.ipynb"
      - "features/data_loading.md"
      - "features/example_data.md"
      - "features/nomenclature.md"
  - "changelog.md"
  - "contributing.md"
