name: Lint
on: [push, pull_request]

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: snok/install-poetry@v1.1.1
    - name: Install dependencies
      run: |
        poetry install
    - name: Run Black
      run: |
        poetry run black --check --diff chiron/
        poetry run black --check --diff tests/
