name: Publish TestPyPI
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: testpypi
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - name: Build package
        run: uv build
      - name: Publish package
        run: uv publish --index-url https://test.pypi.org/legacy/ --token ${{ secrets.TESTPYPI_TOKEN }}
