name: Publish TestPyPi
on:
  release:
    types: [published]
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish to TestPyPi
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    # Dedicated environments with protections for publishing are strongly recommended.
    environment:
      name: testpypi
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1
      - name: Poetry configuration
        env:
          TESTPYPI_TOKEN: ${{ secrets.TESTPYPI_TOKEN }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          # Print a masked version of the token
          echo "TestPyPI Token: ${TESTPYPI_TOKEN:0:8}****"
          poetry config pypi-token.pypi $TESTPYPI_TOKEN
      - name: Build package
        run: |
          poetry build
      - name: Publish package
        run: |
          poetry publish --repository testpypi --username __token__ --password $TESTPYPI_TOKEN
