name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    environment:
      name: pypi
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1
      - name: Poetry configuration
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Build package
        run: |
          poetry build
      - name: Publish package
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          echo "TestPyPI Token: ${TESTPYPI_TOKEN:0:8}****"
          poetry publish --username __token__ --password $PYPI_TOKEN
